import Link from 'next/link'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <div className="text-center">
        <h1 className="text-6xl font-bold text-gray-900 mb-4">
          Streaming1758830864950
        </h1>
        
        <p className="text-xl text-gray-600 mb-8 max-w-2xl">
          A streaming application similar to Netflix, allowing users to watch a variety of movies and TV shows.. Features: User Registration and Login, Content Streaming, Search and Recommendation, Subscription Management
        </p>
        
        <div className="bg-white rounded-lg shadow-lg p-8 max-w-4xl mx-auto">
          <h2 className="text-2xl font-semibold mb-6 text-gray-800">
            🚀 Your Next.js app is ready!
          </h2>
          
          <div className="grid md:grid-cols-2 gap-6 text-left">
            <div className="space-y-4">
              <h3 className="font-semibold text-lg text-gray-800">Tech Stack</h3>
              <ul className="space-y-2 text-gray-600">
                <li className="flex items-center">
                  <span className="mr-2">⚡</span>
                  Next.js 14 with App Router
                </li>
                <li className="flex items-center">
                  <span className="mr-2">📘</span>
                  TypeScript
                </li>
                <li className="flex items-center">
                  <span className="mr-2">🎨</span>
                  Tailwind CSS
                </li>
                <li className="flex items-center">
                  <span className="mr-2">🔐</span>
                  NextAuth.js
                </li>
                <li className="flex items-center">
                  <span className="mr-2">🗄️</span>
                  PostgreSQL
                </li>
              </ul>
            </div>
            
            <div className="space-y-4">
              <h3 className="font-semibold text-lg text-gray-800">Next Steps</h3>
              <ul className="space-y-2 text-gray-600">
                <li className="flex items-center">
                  <span className="mr-2">1️⃣</span>
                  Set up your database
                </li>
                <li className="flex items-center">
                  <span className="mr-2">2️⃣</span>
                  Configure authentication
                </li>
                <li className="flex items-center">
                  <span className="mr-2">3️⃣</span>
                  Start building your app
                </li>
                <li className="flex items-center">
                  <span className="mr-2">4️⃣</span>
                  Deploy to Vercel
                </li>
              </ul>
            </div>
          </div>
          
          <div className="mt-8 flex flex-wrap gap-4 justify-center">
            <Link
              href="/api/hello"
              className="px-6 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
            >
              Test API Route
            </Link>
            <Link
              href="https://nextjs.org/docs"
              target="_blank"
              className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Documentation
            </Link>
          </div>
        </div>
        
        <div className="mt-8 text-sm text-gray-500">
          Generated by{' '}
          <span className="font-semibold text-primary-600">NexaBuilder CLI</span>
        </div>
      </div>
    </main>
  )
}