apiVersion: v1
kind: Namespace
metadata:
  name: nexabuilder
  labels:
    name: nexabuilder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexabuilder-app
  namespace: nexabuilder
  labels:
    app: nexabuilder
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nexabuilder
  template:
    metadata:
      labels:
        app: nexabuilder
        version: v1
    spec:
      containers:
      - name: nexabuilder
        image: 470880515336.dkr.ecr.us-east-1.amazonaws.com/nexabuilder:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: NEXT_PUBLIC_APP_NAME
          value: "Nexa Builder"
        - name: NEXT_PUBLIC_BASE_URL
          value: "https://dev.nexabuilder.net"
        - name: DATABASE_URL
          value: "postgresql://postgresadmin:password@nexabuilder-dev-rds.coz0yeck4uy6.us-east-1.rds.amazonaws.com:5432/nexabuilder"
        - name: DB_HOST
          value: "nexabuilder-dev-rds.coz0yeck4uy6.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "nexabuilder"
        - name: DB_USERNAME
          value: "postgresadmin"
        - name: DB_PASSWORD
          value: "password"
        - name: NEXTAUTH_SECRET
          value: "zYvwtcgU7ddXR9wSKVdA9dZ3d5R9CouvKO+dFsQ6EOg="
        - name: NEXTAUTH_URL
          value: "https://dev.nexabuilder.net"
        - name: OPENAI_API_KEY
          value: "sk-test-key-placeholder"
        - name: AWS_REGION
          value: "us-east-1"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 20
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nexabuilder-service
  namespace: nexabuilder
  labels:
    app: nexabuilder
spec:
  selector:
    app: nexabuilder
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexabuilder-ingress
  namespace: nexabuilder
  labels:
    app: nexabuilder
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: '/api/health'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
spec:
  rules:
  - host: dev.nexabuilder.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexabuilder-service
            port:
              number: 80
